### ISSUE TITLE
Internet permission

### ISSUE THREAD

**Issue by davidmef** [yamin8000/Dooz#105]
I see in https://f-droid.org/en/packages/io.github.yamin8000.dooz/ that version 1.0.8 added the permission "have full network access". What does the game need it for?

**Comment by yamin8000** [comment]
> I see in https://f-droid.org/en/packages/io.github.yamin8000.dooz/ that version 1.0.8 added the permission "have full network access". What does the game need it for?

A very good question and I deeply understand the concern. Starting from the 1.0.5 version, the game has two flavors, one specifically for Iranian App markets that has ads and a free version without ads. The only difference is ads and irMarkets flavors have no advantage over the free ones.
Internet access is added for loading ads, at the time I didn't have the time to enhance the app in a way to remove permission from the free version but I will investigate the problem and remove the Internet permission from the version.
In theory free version has access to the internet but there's no code in the source code of the free version for making a web request.
